name: Build iOS Dylib
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Build Tools
        run: |
          brew install ldid
      - name: Setup Theos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz
          tar -xf iPhoneOS16.5.sdk.tar.xz -C ~/theos/sdks
          rm iPhoneOS16.5.sdk.tar.xz
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Download ImGui Dependencies
        run: |
          chmod +x ./get_imgui.sh
          ./get_imgui.sh
      - name: Build Dynamic Library
        run: |
          export THEOS=~/theos
          make FINALPACKAGE=1
          mkdir -p output
          find .theos/ -name "*.dylib" -exec cp {} output/ \;
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImGuiOverlay-dylib
          path: output/*.dylib
